<?php 


$category = array(

	'1' => 'Architecture',
	'2' => 'Art & Culture',
	'3' => 'Biology & Life Sciences',
	'4' => 'Business & Management',
	'5' => 'Chemistry',
	'6' => 'Communication',
	'7' => 'Computer Science',
	'8' => 'Data Analysis & Statistics',
	'9' => 'Design',
	'10' => 'Economics & Finance',
	'11' => 'Education and Teacher',
	'12' => 'Training',
	'13' => 'Electronics',
	'14' => 'Energy & Earth Sciences',
	'15' => 'Engineering',
	'16' => 'Environmental Studies',
	'17' => 'Ethics',
	'18' => 'Food & Neutrition',
	'19' => 'Health & Safety',
	'20' => 'Humanities',
	'21' => 'History',
	'22' => 'Language',
	'23' => 'Law',
	'24' => 'Literature',
	'25' => 'Math',
	'26' => 'Medicine',
	'27' => 'Physics'


	); 